AWSTemplateFormatVersion: 2010-09-09
Description: Mitjan CloudFormation -testitemplate
#testimuutos
#toinen testimuutos
Resources:

  SNStopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: cfpipeline

